server:
  port: 8002
#  context-path: /qyj_client

debug: false

spring:
  application:
    name: temp
  datasource:
    druid:
      url: jdbc:mysql://47.104.66.21:3306/paris?characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: select 1
      validation-query-timeout: 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 120000
      min-evictable-idle-time-millis: 120000
      remove-abandoned: true
      remove-abandoned-timeout-millis: 7200
      log-abandoned: true
      pool-prepared-statements: false
      max-open-prepared-statements: 20

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.panlei.demo.bean

eureka:
  instance:
    hostname: 47.104.66.21
  client:
    service-url:
      defaultZone: http://47.104.66.21:8001/eureka